# Generated by Django 3.0.2 on 2020-06-02 09:34

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_qty', models.PositiveIntegerField()),
                ('blood_type', models.CharField(max_length=3)),
                ('type_rh', models.CharField(max_length=20)),
                ('donate_date', models.DateField()),
                ('result_date', models.DateField()),
                ('blood_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(help_text='Contact Number', max_length=31)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10)),
                ('type_rh', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(help_text='Contact Number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10)),
                ('type_rh', models.CharField(max_length=20)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_bag_id', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=3)),
                ('type_rh', models.CharField(max_length=20)),
                ('blood_volume', models.PositiveIntegerField()),
                ('recieve_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('blood_status', models.CharField(max_length=20)),
                ('blood_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.BloodDonation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.Donor'),
        ),
    ]
