# Generated by Django 3.0.2 on 2020-06-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodbank', '0002_remove_inventory_blood_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='blood_bag_id',
            field=models.CharField(default='822-96-0904', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
